### PR TITLE
Fixed license URL

### PR DESCRIPTION
**Pull request by jlanng**
Fixed license URL. This was causing an issue for me using an automated tool.

### CODE REVIEW

**Review by tj-planaton — APPROVED** [review]
Thanks a lot.

**Review by rpgmaker — APPROVED** [review]
Thanks

**Comment by rpgmaker** [comment]
I will generate a new nuget package for it. @jlanng .

**Comment by rpgmaker** [comment]
@jlanng, the new nuget version is now available. Thanks again for the contribution.

**Comment by jlanng** [comment]
Thanks @rpgmaker for the quick turnaround, much appreciated

**Pull request merged**
