### PR TITLE
Addressing issue #132

### PR DESCRIPTION
**Pull request by wmjordan**
This commit addressed issue #132 to clean up the NetJSON class, exposing much fewer public methods by moving them into the `NetJSON.Internals` namespace. Those types and methods are still public for the sake of the dynamic assembly feature.

### CODE REVIEW

**Comment by wmjordan** [comment]
The .Net Core and PCL projects were temporary unloaded and thus it failed the build.

**Comment by rpgmaker** [comment]
Don't unload them. The build always fails on the appveyor because it does
not support them. If it compiles locally then it is fine.

Thanks,

**Comment by rpgmaker** [comment]
You can unload the pcl project but leave the .net core because it works fine locally.

**Comment by wmjordan** [comment]
OK.
Currently I don't have the .Net Core tools installed since it is still in preview status.
Previously I installed some _preview_ tools and they could not be uninstalled unless I spent several hours searching the web, trying reinstalling VS, and eventually found solutions from forums. I'd gotten two preview versions and I repeated the above procedure for each of them respectively.
They were terrible nightmares to me. I am hesitated to install it until the final release version comes out.

**Comment by rpgmaker** [comment]
I will look into this merge once i am free.

Thanks for the effort,

**Comment by wmjordan** [comment]
Please take a look at the refactoring of the part calling `StringBuilder.Clear()`.
Previously you used conditional compilation directives to call various versions of that method on different targets. I'd changed the emission of calling that method to an extension method to `ILGenerator`.
````C#
void EmitClearStringBuilder(this ILGenerator il) {
      // conditionally emit calling opcodes on various targets
}
````
Therefore, the most conditional directives for `StringBuilder.Clear` could be substituted by an extension method call `il.EmitClearStringBuilder()`.

I found this pattern can simplify other method calls too.
You have quite a lot of `static` fields of `MethodInfo` which are used later for `il.Emit(OpCodes.Call, methodInfo)` or `il.Emit(OpCodes.Call, methodInfo)`. We can use extension methods to eliminate those `MethodInfo` fields, and perhaps some `Type` fields for those `MethodInfo` fields.

For instance, by replacing `il.Emit(OpCodes.Call, _typeGetTypeFromHandle)` with `il.EmitGetTypeForHandleOnType()` (an extension method), we no longer need the `_typeGetTypeFromHandle` field in `NetJSON` class any more.

**Comment by rpgmaker** [comment]
OK

**Comment by rpgmaker** [comment]
I will look into the pull request in detail and get back to you on any questions that I might have. Sorry I have not been too involved. Just got back in town.

Thanks,

**Comment by wmjordan** [comment]
It's alright. I am also busy at these days on some projects.
I found that using internal extension methods, we would be able to refactor more internal code out of _NetJSON.cs_ and make it cleaner, since some part of code will no longer be dependent on private fields of the `NetJSON` type.

**Comment by rpgmaker** [comment]
I get your branch and i am trying to build locally but i get the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'GetUninitializedObject' does not exist in the current context	NetJSON.Core..NETStandard,Version=v1.6	C:\Users\Olamide\Desktop\Folders\NetJSON-refactor\NetJSON\NetJSON\NetJSON.Internals.cs	148	Active

I could fix it, but that one of the methods was moved

**Comment by rpgmaker** [comment]
In regards to the following code:


```
public static void EmitClearStringBuilder(this ILGenerator il) {
#if !NET_35
			il.Emit(OpCodes.Callvirt, typeof(StringBuilder).GetMethod("Clear"));
#else
			il.Emit(OpCodes.Call, typeof(StringBuilder35Extension).GetMethod("Clear"));
#endif
}
```

For performance purpose (Might be a little of micro optimization). I would recommend caching the GetMethod for both StringBuilder and StringBuilder35Extension value. Since emit will be used for generating deserialize/serialize methods per type, and the clear method never change so there is no benefit of getting it all the time.

**Comment by rpgmaker** [comment]
If you do decide to use EmitGetTypeForHandleOnType similar to the clear method. I will suggest also using the cached methodinfo also.

**Comment by wmjordan** [comment]
Previously I unloaded the Core project for my VS did not have the tool. Thus `GetUninitializedObject` might be left out. I am sorry for missing it out there.

I agree that `StringBuilder.Clear` no longer changes after reflection. I understand your consideration. However, since we have cached the serializers and deserializers in the `NetJSONCachedSerializer`, after building all necessary serializers, we no longer need to generate dynamic IL code any more. The caching of `MethodInfo`s **may** benefit reducing the start up time but it does not help afterward but waste memory.
* How much the caching of `MethodInfo`s can help reduce the start up time could vary according to different projects. For instance, one of my project majorly serialize `int`, `double` and `string` types only. Thus, the caching of `decimal`, `float`, `DateTime`, `byte`, `short`, `ushort`, etc. related methods is not useful and it increases the initialization time of the static constructor of the `NetJSON` class.

What's your viewpoint to this?

**Comment by rpgmaker** [comment]
The viewpoint is that the allocated memory to keep the methodinfo is relatively small in footprint since it will only store it methodinfo and the scenarios where multiple types are been used a lot will require the cost of get type and get method for each of those types. 

There are apps that serialize dynamic types in their apps and lot of object model, avoiding just that extra time spent will be noticeable in those environments. 

For example in my app, I generate dynamic types based on the json string payload that I get and will affect my app overtime. I do understand that after serializer is cached everything will be great, but it will be nice to avoid the start up cost by trading it for a little memory.

Thanks for the effort overall, i will try to review the rest of the code before the end of the week so I can fix the other open bugs.

Thanks,

**Pull request merged**
