### PR TITLE
fix to serialize interfaces\abstract types

### PR DESCRIPTION
**Pull request by galziv**
Try to get Newobj only for types with constructor. Without condition an exception is thrown.

### CODE REVIEW

**Comment by rpgmaker** [comment]
This will cause an exception since opcodes.stloc is still going to be called when their is no value on the stack to pop. It will be better to use an attribute to get the correct type to initialize when a constructor does not exists.

Thanks,

**Comment by galziv** [comment]
Sorry, but I'm not that familiar with the framework. What do you mean by "using an attribute"? can you show an example or refer me to the relevant doc?
Thanks in advance.

**Comment by rpgmaker** [comment]
Something like this.https://msdn.microsoft.com/en-us/library/hh194292(v=vs.110).aspx

**Comment by galziv** [comment]
I'll review. Thank you for the prompt replies!

**Comment by rpgmaker** [comment]
I am closing the pull request since I can merge because it will break current functionality.

Thanks,

**Pull request closed without merging**
