### PR TITLE
Migrated solution to Visual Studio 2017

### PR DESCRIPTION
**Pull request by NimaAra**
This was done to address: #165.

Note there are currently the following tests failing:
* `TestSerializeDateUtcNowWithMillisecondDefaultFormatUtc`
* `TestSerializeComplexTuple`

The first one has always been failing for me even on the old solution file and the second one I cannot validate as I only have _VS2017_ installed on my machine and opening the old solution file prompts for a migration.

I have also included the `Nuget-Pack.bat` to which you can pass the version number to release which generates 2 _NuGet_ packages one with the source and _pdb_ files included. You can run as: `NuGet-Pack 1.2.3.4`

Kindly have a look and validate.

### CODE REVIEW

**Comment by rpgmaker** [comment]
Thanks I will review them

**Comment by rpgmaker** [comment]
I will verify the two tests myself. I believe they were working fine

**Comment by rpgmaker** [comment]
I can't compile it in my 2017 enterprise. The (net35) is not working for me, do I need to download anything to make it work?

**Comment by rpgmaker** [comment]
image

**Comment by NimaAra** [comment]
Which version of _VS_ and _.NET Core_ are you using?
image

**Comment by rpgmaker** [comment]
15.2 Enterprise

**Comment by rpgmaker** [comment]
image

**Comment by NimaAra** [comment]
Investigating...

**Comment by NimaAra** [comment]
That's strange, I just did a clone on another machine and it was built just fine. Just to confirm, you are trying to build: https://github.com/NimaAra/NetJSON.git right?

Also can you clone one of my other projects which has a similar structure and see if you can build that? e.g. https://github.com/NimaAra/Easy.MessageHub.git

**Comment by rpgmaker** [comment]
I cloned https://github.com/NimaAra/NetJSON.git locally. Do you have .net 4.7 installed like I do?

**Comment by NimaAra** [comment]
No, I don't, let me try it with _.NET 4.7_ then.

**Comment by NimaAra** [comment]
Yep, it works fine with _.NET 4.7_ installed as well. Can you make sure you have the _.NET 3.5_ _SDK_ installed?

**Comment by rpgmaker** [comment]
The error I got was for both 1.6 standard and 3.5 framework. I will check if I have the sdk.

**Comment by NimaAra** [comment]
I believe that's because you are missing: `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client`

Try removing this in the `NetJSON.csproj`:

```xml
  <PropertyGroup>
    <!-- This is a workaround for: https://github.com/Microsoft/msbuild/issues/1333 -->
    <FrameworkPathOverride Condition="'$(TargetFramework)' == 'net35'">C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client</FrameworkPathOverride>
  </PropertyGroup>
```
We will need this workaround however let us see it solves the build at least for _net35_.

**Comment by rpgmaker** [comment]
I am still getting the same error after removing it.

image


image

**Comment by NimaAra** [comment]
That's weird, I cannot think of anything else. can you check the output of: `dotnet --info`?

**Comment by rpgmaker** [comment]
I will try it out. Thanks

**Comment by rpgmaker** [comment]
image

**Comment by NimaAra** [comment]
Hmm.. that's also identical to mine, no idea why it doesn't build. Did you find out whether you have _.NET 3.5_ _SDK_?

**Comment by rpgmaker** [comment]
Did not try it. I will search for it

**Comment by rpgmaker** [comment]
i have 3.5 installed on my machine. I don't have the profile folder, but i have the rest of the other 3.5 paths.

I will try to test it and figured out what my machine could be missing.

Thanks,

**Comment by NimaAra** [comment]
Are you sure you have the _.NET 3.5_ _SDK_ and not the runtime? FYI, [HERE](https://www.microsoft.com/en-gb/download/details.aspx?id=3138)'s the _SDK_.

**Comment by rpgmaker** [comment]
I downloaded it but did not install it. Because I was not sure if it will work for my windows 10

**Comment by rpgmaker** [comment]
I will install it and see if it helps.

Thanks

**Comment by rpgmaker** [comment]
I installed it and it made no different :)

**Comment by NimaAra** [comment]
Not sure what else to suggest :-(

**Comment by rpgmaker** [comment]
Don't worry I will figure something out.

**Comment by rpgmaker** [comment]
I do notice something weird about my property page for my solution. The target framework is blank

image

**Comment by NimaAra** [comment]
Yeah that's fine, it is blank for me as well. this is due to the project targeting multi platforms I believe the _VS_tooling will be updated to have a more clear support for such configuration.

**Comment by rpgmaker** [comment]
I am thinking that I will just create a new project and manually copy the files to it and see if that works. I am not able to get it to work with net35 even though the sdk is installed and everything works fine for .net 3.5 project in the old solution.

**Comment by NimaAra** [comment]
Sure give it a try. The old solution is not the same as the new. In the new solution the projects have been migrated to the new `cjsproj` format. I would be interested to see if you could get a _VM_ with a fresh install of _VS2017_ or another machine to rule out there's nothing wrong with your system.

**Comment by buildcenter** [comment]
howdy. do you have net35 installed? quick powershell check `Get-WindowsOptionalFeature -Online -FeatureName NetFx3` will tell you.

I normally do my builds in a hyper v vm, just to avoid this sort of thing...

**Comment by NimaAra** [comment]
@buildcenter Just ran it and got: 

```text
FeatureName      : NetFx3
DisplayName      : .NET Framework 3.5 (includes .NET 2.0 and 3.0)
Description      : .NET Framework 3.5 (includes .NET 2.0 and 3.0)
RestartRequired  : Possible
State            : Enabled
CustomProperties :
                   \FWLink : http://go.microsoft.com/fwlink/?LinkId=296822
```

**Comment by rpgmaker** [comment]
image

I got same thing too :)

**Comment by buildcenter** [comment]
sorry that wasn't of help. perhaps running on a fresh win10 install (in a vm) would be the best recourse.

**Comment by NimaAra** [comment]
@buildcenter Have you tried building this pull request yourself? does it work for you?

**Comment by NimaAra** [comment]
@rpgmaker Any updates? FYI, I just made a similar migration to [VaderSharp](https://github.com/codingupastorm/vadersharp) [HERE](https://github.com/codingupastorm/vadersharp/pull/12)

**Comment by rpgmaker** [comment]
I tried different things such as installation of 3.5 sdk for 2017. I wanted to test if I was missing a plug-in for it. I am going to try a new project tomorrow. 

Sorry again for struggling with this.

Thanks,

**Comment by NimaAra** [comment]
no problem, I am interested to find out what is causing this.

**Comment by rpgmaker** [comment]
i figured it out. it was failing because i had registered a path in package source that did not exists and packages were failing to get restored which ultimately caused the failure. I found this out when i tried to move the project to a new project.

Thanks,

**Comment by rpgmaker** [comment]
The TestSerializeComplexTuple test is failing. It seems like the test cases does not account for the proper reference to NetJSON.Tuple vs System.Tuple.

**Comment by NimaAra** [comment]
Okay, that's great! One step closer :-)

**Comment by rpgmaker** [comment]
Much closer indeed :) . One last request. is it possible to have the Nuget-pack.bat automatically use the version of the assemblies to create the nuget package instead of using 1.0.0.0 by default?

Thanks,

**Comment by NimaAra** [comment]
With regards to the `NetJSON.Tuple`, I have set it to compile only when it's targeting _net35_ so if the tests are being run as _netstandard_ then they will be referencing `System.Tuple`. 

To be fair I did not understand why you had to define the `Tuple`, couldn't you use the `System.Tuple`? Or even better how about the newly added [`System.ValueTuple`](https://msdn.microsoft.com/en-us/library/system.valuetuple(v=vs.110).aspx) which is actually a struct.

**Comment by NimaAra** [comment]
With regards to the packaging, I have set it up the way I release my projects.

Here's basically how it is intended to be used:

I have 2 _continuous integration_ jobs running (_AppVeyor_/_Jenkins_/_TeamCity_ etc).
1. which monitors _GitHub_ and runs the test after every commit.
2. only monitors the _release_ tags that I create on _GitHub_ e.g. v1.2.3

As soon as it detects the tag, it takes the _1.2.3_ and appends the build number e.g. _110_ and produces the final version number of _1.2.3.110_ which is the number passed in to _Nuget-pack.bat_.

Overall this approach makes the managing of my _OSS_ projects much simpler with no headache at all.

Alternatively, you can get rid of [AssemblyInfo.cs](https://github.com/NimaAra/NetJSON/blob/master/NetJSON/Properties/AssemblyInfo.cs) and put the versions inside the _csproj_ file just like I have done for let's say [THIS](https://github.com/NimaAra/Easy.Logger/blob/master/Easy.Logger/Easy.Logger.csproj) project you can then do a simple _xml_ or _regex_ modification of the _csproj_ in the _bat_ file and repalce it with the version you want which basically achieves what you want.

I honestly prefer the first approach as it's much cleaner and automatically triggered by _GitHub_. You essentially manage all your releases from _GitHub_ directly.

Hope this helps.

**Comment by rpgmaker** [comment]
It was done to support tuple in .net 3.5. And to avoid writing code inline to avoid tuple for 3.5. you could change the code to conditionally only support tuple when it is not 3.5.

Thanks,

**Comment by rpgmaker** [comment]
The process make sense I guess. I always wanted to specific the version to indicate major and minor release. Let me think through it.

Thanks,

**Comment by NimaAra** [comment]
You can still have full control over _major_._minor_. The tag name that you create, dictates the semantic versioning. You can create one tag named _v1.2.0_ and if you later want to patch it you can create _v1.2.1_ or if you want to do a minor release you then create _v1.3.0_. etc.

**Comment by NimaAra** [comment]
So you want me to disable _Tuple_ support for _net35_?

**Comment by rpgmaker** [comment]
Yep. Go ahead and make the changes to only use tuple for version higher than 3.5.

Thanks,

**Comment by rpgmaker** [comment]
If it support the control of minor and major then I guess the changes for versioning is fine with me.

Thanks,

**Comment by NimaAra** [comment]
It does not look that straight forward. For some reason the _IL_ does not respect the conditional compilation flags. So I cannot conditionally include `System.Tuple` vs `NetJSON.Tuple`.....

This is going to be interesting to fix! :-)

**Comment by rpgmaker** [comment]
Yep. I was waiting for you to mention that 😀

**Comment by rpgmaker** [comment]
Simple remove the Tuple class that I created for 3.5 and put condition around the TupleContainer to only create it when it is not 3.5. and use GetType to get reference to TupleContainer rather than using of typeof(...). That might help you reduce code changes since .net 4.0 and above supports tuple

**Comment by NimaAra** [comment]
Okay, I will have a look once I get the chance.

**Comment by NimaAra** [comment]
@rpgmaker it doesnn't like `_tupleContainerType = Type.GetType("NetJSON.Internals.TupleContainer")`. It's throwing `TypeInitializationException` exception all over the place.

```
System.TypeInitializationException: The type initializer for 'NetJSON.NetJSON' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.

```

**Comment by rpgmaker** [comment]
It should have resolved properly. I am going to try it out tonight myself and see what it does 

Thanks,

**Comment by rpgmaker** [comment]
I could not come to a solution from my side. You could try having one TupleContainer and then moving the tuple definition of 3.5 outside from it current definition. The only error I am getting is conversion issue between NetJSON.Tuple and System.Tuple for one of the unit test. Beyond that, everything is fine.

**Comment by NimaAra** [comment]
Not far :-( tried and failed miserably a couple of times and frankly I have been busy with other stuff. It's ridiculous how something so tiny can be so annoying!

**Comment by rpgmaker** [comment]
Could you please resolve the conflict? I just fixed some other issues.

Thanks,

**Comment by rpgmaker** [comment]
I am guessing you want me to finish this pr myself? :)

**Comment by NimaAra** [comment]
Feel free to modify it as you see fit, I am stuck with a ton of stuff that limit my availability for doing any OSS for the time being. :-(

**Comment by rpgmaker** [comment]
No problem. I will mess around with it this weekend if I get a chance.

Thanks,

**Comment by rpgmaker** [comment]
Sorry i have not been able to merge this yet. Still have some open items to fix first.

**Comment by rpgmaker** [comment]
This is still in my view. I have a lot to do to get this working with current code.

**Comment by NimaAra** [comment]
Unfortunately I have had too much on my plate as well otherwise I would have taken another look :-(

**Comment by rpgmaker** [comment]
Np. Thanks for starting it in the first place.

**Pull request closed without merging**
